//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Percentage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Percentage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedResources.Properties.Percentage", typeof(Percentage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Acc.
        /// </summary>
        public static string AutoAcc {
            get {
                return ResourceManager.GetString("AutoAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Number.
        /// </summary>
        public static string Badge {
            get {
                return ResourceManager.GetString("Badge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cur Month.
        /// </summary>
        public static string CurMonth {
            get {
                return ResourceManager.GetString("CurMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cur Month w/SA.
        /// </summary>
        public static string CurMonthWithSilents {
            get {
                return ResourceManager.GetString("CurMonthWithSilents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill Com.
        /// </summary>
        public static string DrillCom {
            get {
                return ResourceManager.GetString("DrillCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill Dpt.
        /// </summary>
        public static string DrillDpt {
            get {
                return ResourceManager.GetString("DrillDpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Day.
        /// </summary>
        public static string FireDay {
            get {
                return ResourceManager.GetString("FireDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Night.
        /// </summary>
        public static string FireNight {
            get {
                return ResourceManager.GetString("FireNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet com.
        /// </summary>
        public static string MeetCom {
            get {
                return ResourceManager.GetString("MeetCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet Dpt.
        /// </summary>
        public static string MeetDpt {
            get {
                return ResourceManager.GetString("MeetDpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Com.
        /// </summary>
        public static string MiscCom {
            get {
                return ResourceManager.GetString("MiscCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescue Day.
        /// </summary>
        public static string RescueDay {
            get {
                return ResourceManager.GetString("RescueDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescue Night.
        /// </summary>
        public static string RescueNight {
            get {
                return ResourceManager.GetString("RescueNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent.
        /// </summary>
        public static string Silent {
            get {
                return ResourceManager.GetString("Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Com.
        /// </summary>
        public static string TrainCom {
            get {
                return ResourceManager.GetString("TrainCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Dpt.
        /// </summary>
        public static string TrainDpt {
            get {
                return ResourceManager.GetString("TrainDpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YTD.
        /// </summary>
        public static string YTD {
            get {
                return ResourceManager.GetString("YTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YTD w/SA.
        /// </summary>
        public static string YTDWithSilents {
            get {
                return ResourceManager.GetString("YTDWithSilents", resourceCulture);
            }
        }
    }
}
