//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProbationDrillDates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProbationDrillDates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedResources.Properties.ProbationDrillDates", typeof(ProbationDrillDates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4/19/2020.
        /// </summary>
        public static string April_Probationary_Drill {
            get {
                return ResourceManager.GetString("April Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8/9/2020.
        /// </summary>
        public static string August_Probationary_Drill {
            get {
                return ResourceManager.GetString("August Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2020.
        /// </summary>
        public static string December_Probationary_Drill {
            get {
                return ResourceManager.GetString("December Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2/18/2020.
        /// </summary>
        public static string February_Probationary_Drill {
            get {
                return ResourceManager.GetString("February Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/19/2020.
        /// </summary>
        public static string January_Probationary_Drill {
            get {
                return ResourceManager.GetString("January Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7/19/2020.
        /// </summary>
        public static string July_Probationary_Drill {
            get {
                return ResourceManager.GetString("July Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6/16/2020.
        /// </summary>
        public static string June_Probationary_Drill {
            get {
                return ResourceManager.GetString("June Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3/17/2020.
        /// </summary>
        public static string March_Probationary_Drill {
            get {
                return ResourceManager.GetString("March Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5/17/2020.
        /// </summary>
        public static string May_Probationary_Drill {
            get {
                return ResourceManager.GetString("May Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11/17/2020.
        /// </summary>
        public static string November_Probationary_Drill {
            get {
                return ResourceManager.GetString("November Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10/11/2020.
        /// </summary>
        public static string October_Probationary_Drill {
            get {
                return ResourceManager.GetString("October Probationary Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9/15/2020.
        /// </summary>
        public static string September_Probationary_Drill {
            get {
                return ResourceManager.GetString("September Probationary Drill", resourceCulture);
            }
        }
    }
}
