//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Properties.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Percentage File.
        /// </summary>
        internal static string badPercentageFile {
            get {
                return ResourceManager.GetString("badPercentageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Probationary Resource Manager.
        /// </summary>
        internal static string badProbieResource {
            get {
                return ResourceManager.GetString("badProbieResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Resource Manager in Resource Manager Collection.
        /// </summary>
        internal static string badResourceManager {
            get {
                return ResourceManager.GetString("badResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Roster File.
        /// </summary>
        internal static string badRosterFile {
            get {
                return ResourceManager.GetString("badRosterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create String Resource Manager.
        /// </summary>
        internal static string badStringResource {
            get {
                return ResourceManager.GetString("badStringResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Training File.
        /// </summary>
        internal static string badTrainingFile {
            get {
                return ResourceManager.GetString("badTrainingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string delimiters {
            get {
                return ResourceManager.GetString("delimiters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\DepartmentPct.xml.
        /// </summary>
        internal static string departmentPctXMLPath {
            get {
                return ResourceManager.GetString("departmentPctXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\DepartmentTraining.csv.
        /// </summary>
        internal static string DepartmentTrainingPath {
            get {
                return ResourceManager.GetString("DepartmentTrainingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\DepartmentTraining.xml.
        /// </summary>
        internal static string departmentTrainingXMLPath {
            get {
                return ResourceManager.GetString("departmentTrainingXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\DepartmentPct.csv.
        /// </summary>
        internal static string MemberPercentagePath {
            get {
                return ResourceManager.GetString("MemberPercentagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\MemberPercentage.xml.
        /// </summary>
        internal static string memberPercentageXMLPath {
            get {
                return ResourceManager.GetString("memberPercentageXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\Members.xml.
        /// </summary>
        internal static string memberXMLPath {
            get {
                return ResourceManager.GetString("memberXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\PESH.csv.
        /// </summary>
        internal static string PESHTrainingPath {
            get {
                return ResourceManager.GetString("PESHTrainingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\PESHTraining.xml.
        /// </summary>
        internal static string peshTrainingXMLPath {
            get {
                return ResourceManager.GetString("peshTrainingXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\ProbationPercentage.csv.
        /// </summary>
        internal static string ProbationPercentagePath {
            get {
                return ResourceManager.GetString("ProbationPercentagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\ProbationPercentage.xml.
        /// </summary>
        internal static string probationPercentageXMLPath {
            get {
                return ResourceManager.GetString("probationPercentageXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\ProbationTraining.csv.
        /// </summary>
        internal static string ProbationTrainingPath {
            get {
                return ResourceManager.GetString("ProbationTrainingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\ProbationTraining.xml.
        /// </summary>
        internal static string probationTrainingXMLPath {
            get {
                return ResourceManager.GetString("probationTrainingXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\Refresher.csv.
        /// </summary>
        internal static string RefresherTrainingPath {
            get {
                return ResourceManager.GetString("RefresherTrainingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\RefresherTraining.xml.
        /// </summary>
        internal static string refresherTrainingXMLPath {
            get {
                return ResourceManager.GetString("refresherTrainingXMLPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster File Parser Failed Column Check.
        /// </summary>
        internal static string rosterParserFailedCheck {
            get {
                return ResourceManager.GetString("rosterParserFailedCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\DataFiles\DepartmentRoster.csv.
        /// </summary>
        internal static string RosterPath {
            get {
                return ResourceManager.GetString("RosterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Field Parser Failed To Open.
        /// </summary>
        internal static string textFieldParserFailedOpen {
            get {
                return ResourceManager.GetString("textFieldParserFailedOpen", resourceCulture);
            }
        }
    }
}
